CREATE TABLE goals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    novel_id integer NOT NULL,
    words integer NOT NULL,
    start date DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finish date,
    curve character varying(10) DEFAULT 'linear'::character varying NOT NULL,
    repeat boolean DEFAULT false NOT NULL,
    removed timestamp with time zone,
    name text,
    parent_id integer,
    CONSTRAINT goals_repeat_finish_presence CHECK (
CASE
    WHEN repeat THEN (finish IS NOT NULL)
    ELSE true
END),
    CONSTRAINT goals_start_finish_gt CHECK (
CASE
    WHEN (finish IS NULL) THEN true
    ELSE (finish > start)
END),
    CONSTRAINT goals_words_minimum CHECK ((words > 0))
);

COMMENT ON COLUMN goals.words IS 'Wordcount to reach, counting from the moment the goal starts';
COMMENT ON COLUMN goals.start IS 'A date, re-interpreted in application code to mean the right thing in the user’s current timezone';
COMMENT ON COLUMN goals.finish IS 'Similarly to start. A goal finishes on the end of its finish day';
COMMENT ON COLUMN goals.curve IS 'The curve to be used for calculating words to go at a date';
COMMENT ON COLUMN goals.repeat IS 'Whether the goal should be repeated when it reaches its finish';
COMMENT ON COLUMN goals.removed IS 'If the goal was deleted, and when';
COMMENT ON COLUMN goals.name IS 'An optional name for human-friendly disambiguation';
COMMENT ON COLUMN goals.parent_id IS 'This is both to explicit the repeat parent/child relationships, and to disambiguate whether a goal should be considered past (“has a child”) in some odd timezone-of-database-server-related cases';
