CREATE TYPE name_kind AS ENUM (
    'male',
    '-male',
    'female',
    '-female',
    'enby',
    '-enby',
    'latin',
    '-latin',
    'english',
    '-english',
    'afram',
    '-afram',
    'indian',
    '-indian',
    'maori',
    '-maori',
    'pacific',
    '-pacific',
    'mideast',
    '-mideast',
    'maghreb',
    '-maghreb',
    'easteuro',
    '-easteuro',
    'french',
    '-french',
    'amerindian',
    '-amerindian',
    'aboriginal',
    '-aboriginal'
);

CREATE TABLE names (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    surname boolean DEFAULT false NOT NULL,
    kinds name_kind[],
    source text,
    added timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    frequency double precision DEFAULT 1.0 NOT NULL,
    CONSTRAINT names_frequency_max CHECK ((frequency <= (100)::double precision)),
    CONSTRAINT names_frequency_min CHECK ((frequency >= (0)::double precision))
);

CREATE INDEX names_frequency_idx ON names USING btree (frequency);
CREATE INDEX names_kinds_idx ON names USING gin (kinds);
CREATE INDEX names_name_idx ON names USING btree (name);
CREATE INDEX names_source_idx ON names USING btree (source);

COMMENT ON COLUMN names.name IS 'All in lowercase, spaces allowed but not preferred';
COMMENT ON COLUMN names.surname IS 'Whether the name is a surname';
COMMENT ON COLUMN names.kinds IS 'Male/female/enby plus the rough ethnic provenance';
COMMENT ON COLUMN names.source IS 'Freeform *short* source description/identifier';
COMMENT ON COLUMN names.frequency IS 'Mostly ignored. Frequency from the source.';
