CREATE TABLE novels (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    started timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name character varying(255),
    finished boolean DEFAULT false NOT NULL,
);

CREATE INDEX novels_user_id_index ON novels USING btree (user_id);

COMMENT ON COLUMN novels.started IS 'When the novel was actually started';
COMMENT ON COLUMN novels.name IS 'Aka title';
COMMENT ON COLUMN novels.finished IS 'Novels marked finished cannot be updated';
