CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id bigint NOT NULL,
    nick character varying(255),
    nano_user character varying(255),
    first_seen timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_seen timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
    tz character varying(50) DEFAULT 'Pacific/Auckland'::character varying NOT NULL,
);

CREATE INDEX users_discord_id_idx ON users USING btree (discord_id);
CREATE INDEX users_nano_user_idx ON users USING btree (nano_user);
CREATE INDEX users_nick_idx ON users USING btree (nick);

COMMENT ON COLUMN users.discord_id IS 'The opaque ID Discord uniquely assigns each user';
COMMENT ON COLUMN users.nick IS 'The latest Discord nick the user was seen using';
COMMENT ON COLUMN users.nano_user IS 'NaNoWriMo participant name, as submitted by the user';
COMMENT ON COLUMN users.first_seen IS 'When the user was first seen by the bot';
COMMENT ON COLUMN users.last_seen IS 'When the user was last seen by the bot, smoothed somewhat';
COMMENT ON COLUMN users.updated IS 'Not counting last_seen updates';
