CREATE TABLE wars (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
    start timestamp with time zone NOT NULL,
    seconds integer NOT NULL,
    cancelled timestamp with time zone,
    creator_id integer NOT NULL,
    canceller_id integer,
    channels text[] NOT NULL,
    started boolean DEFAULT false NOT NULL,
    ended boolean DEFAULT false NOT NULL,
);

COMMENT ON COLUMN wars.start IS 'When this war is slated to start';
COMMENT ON COLUMN wars.seconds IS 'How long the war will run for';
COMMENT ON COLUMN wars.creator_id IS 'Who created this war. Note the creator may leave the war.';
COMMENT ON COLUMN wars.cancelled IS 'If the war is cancelled, and when that was done';
COMMENT ON COLUMN wars.canceller_id IS 'If the war was cancelled by a known user, who that is';
COMMENT ON COLUMN wars.channels IS 'What channels this war should broadcast to';
COMMENT ON COLUMN wars.started IS 'If this war was announced as having started';
COMMENT ON COLUMN wars.ended IS 'If this war was announced as having ended';

CREATE TABLE wars_members (
    user_id integer NOT NULL,
    war_id integer NOT NULL
);

ALTER TABLE ONLY wars_members ADD CONSTRAINT wars_members_pkey PRIMARY KEY (user_id, war_id);
CREATE INDEX wars_members_war_id_user_id_index ON wars_members USING btree (war_id, user_id);
