CREATE TABLE wordcounts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    novel_id integer NOT NULL,
    words integer NOT NULL,
    as_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT wordcounts_words_minimum CHECK ((words >= 0))
);

ALTER TABLE ONLY wordcounts ADD CONSTRAINT wordcounts_novel_id_as_at_unique UNIQUE (novel_id, as_at);

CREATE INDEX wordcounts_as_at_index ON wordcounts USING btree (as_at);
CREATE INDEX wordcounts_novel_id_index ON wordcounts USING btree (novel_id);

COMMENT ON COLUMN wordcount.words IS 'The absolute number of words in the novel at the recorded moment';
COMMENT ON COLUMN wordcount.as_at IS 'The moment when the amount of words was recorded';
COMMENT ON COLUMN wordcount.created IS 'The moment when this record was created';
